name: deukki
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # ======== Firebase API =========
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1

  provider: ^4.3.2
  sqflite: ^1.3.1
  http: ^0.12.2
  shared_preferences: ^0.5.10
  permission_handler: ^5.0.1+1
  #flutter_audio_recorder: ^0.5.5
  path_provider: ^1.6.11
  path: ^1.7.0

  # ======== Social Login API =========
  kakao_flutter_sdk: ^0.4.2
  flutter_facebook_login: ^3.0.0

  # ======== Kakao SDK dependencies =========
  dio: ^3.0.10
  json_annotation: ^3.0.1
  platform: ^2.2.1
  package_info: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/app_logo_white.png
    - images/app_logo_yellow.png
    - images/apple_logo.png
    - images/arrow_back_btn.png
    - images/back_btn.png
    - images/flag_active.png
    - images/flag_normal.png
    - images/google_g_logo.png
    - images/icon_bookmark_active.png
    - images/icon_bookmark_normal.png
    - images/icon_clear.png
    - images/icon_empty_star.png
    - images/icon_face.png
    - images/icon_full_star.png
    - images/icon_half_star.png
    - images/icon_hearing.png
    - images/icon_keyboard_voice.png
    - images/icon_play.png
    - images/icon_speaker.png
    - images/img_basic_purple.png
    - images/img_basic.png
    - images/img_business_green.png
    - images/img_business.png
    - images/img_practice_blue.png
    - images/img_practice.png
    - images/img_word_yellow.png
    - images/img_word.png
    - images/kakao_logo.png
    - images/kakao_logo_yellow.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: TomoneyRound
      fonts:
        - asset: fonts/TmoneyRoundWindRegular.ttf
        - asset: fonts/TmoneyRoundWindExtraBold.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

