name: deukki
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.4+28  # build name: 1.0.0 / build number: +1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # ======== Firebase API ========= #
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  firebase_analytics: ^6.3.0
  firebase_crashlytics: ^0.2.4
  firebase_messaging: ^7.0.3

  provider: ^4.3.2
  sqflite: ^1.3.1
  http: ^0.12.2
  shared_preferences: ^0.5.10
  permission_handler: ^5.0.1+1
  flutter_audio_recorder: ^0.5.5
  path_provider: ^1.6.11
  path: ^1.7.0
  json_serializable: ^3.4.1
  build_runner: ^1.9.0
  dotted_border: ^1.0.6
  just_audio: ^0.6.5
  volume: ^1.0.1
  hardware_buttons: ^1.0.0
  lottie: ^0.7.0+1
  webview_flutter: ^1.0.7
  crypto: ^2.1.5
  device_info: ^1.0.0
  intl: ^0.16.1
  url_launcher: ^5.7.10
  scroll_to_index: ^1.0.6

  # ======== In-App Purchase ========= #
  in_app_purchase: ^0.3.4+16

  # ======== Social Login API ========= #
  kakao_flutter_sdk: ^0.5.2
  flutter_facebook_auth: ^0.3.1
  google_sign_in: ^4.5.3
  sign_in_with_apple: ^2.5.4

  # ======== Kakao SDK dependencies ========= #
  dio: ^3.0.10
  json_annotation: ^3.0.1
  platform: ^2.2.1
  package_info: ^0.4.3

  # ======== Staggerd Grid View ======== #
  flutter_staggered_grid_view: ^0.3.2

  # ======== Amplitude ======== #
  amplitude_flutter: ^2.0.0

  # ======== In-App Review ======== #
  in_app_review: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: TmoneyRound
      fonts:
        - asset: assets/fonts/TmoneyRoundWindRegular.ttf
        - asset: assets/fonts/TmoneyRoundWindExtraBold.ttf
          weight: 700
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Black.otf
          weight: 900
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

